
FROM nginx 
# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/ShangHai /etc/localtime \
  && echo "Asia/Shanghai" > /etc/timezone \
  && dpkg-reconfigure -f noninteractive tzdata
COPY ./dist/ /etc/nginx/html/fe
COPY   nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
WORKDIR /etc/nginx/
CMD ["nginx","-g","daemon off;"]