FROM openjdk:8-jdk-alpine
ARG JAR_FILE=*.jar
COPY ${JAR_FILE} /app/app.jar
# COPY application.properties /app/
ENV TZ Asia/Shanghai
RUN apk add tzdata && cp /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && apk del tzdata
# 容器暴露的端口
EXPOSE 8080/tcp
# ,"-Dfile.encoding=utf-8" 
ENTRYPOINT   ["java","-jar","/app/app.jar"]